name: business
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.1.0 
  google_fonts: ^5.0.0
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.18.0  # Move intl here, not nested under flutter_test
  flutter_lints: ^4.0.0
  carousel_slider: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/98.jpg
    - assets/kick.jpg
    - assets/max.jpg
    - assets/kick2.jpg
    
